[CUSTOM]
chroma_multiplier=5.5
color=
color_last=#d0265c
custom_colors_list=
custom_colors_list_last=#d0265c #74e448 #326b2bf #532066 #297d81 #ccc1c1
dark_brightness_multiplier=1
dark_saturation_multiplier=1
darker_window_list=
disable_konsole=false
fetch_colors=false
gui_custom_exec_location=
iconsdark=Reversal-green
iconslight=Reversal-green
klassy_windeco_outline=true
konsole_blur=true
konsole_opacity=75
konsole_opacity_dark=75
light=true
light_brightness_multiplier=1
light_saturation_multiplier=1
main_loop_delay=1
manual_fetch=false
monitor=0
ncolor=0
on_change_hook=
once_after_change=false
pause_mode=false
plasma_follows_scheme=false
pywal=true
pywal_follows_scheme=false
pywal_light=false
scheme_variant=0
screenshot_delay=900
screenshot_only_mode=false
sierra_breeze_buttons_color=true
startup_delay=0
titlebar_opacity=0
titlebar_opacity_dark=0
titlebar_opacity_override=false
tone_multiplier=1
toolbar_opacity=0
toolbar_opacity_dark=0
use_startup_delay=false
